import { createRequire } from "node:module"
import { defineConfig } from "vite"
import react from "@vitejs/plugin-react"

// dist/buildInfo.cjs is generated by ./generateBuildInfo.sh (npm run prepare / prebuild)
// and is the single source of truth for the build version, shared with the server
const require = createRequire(import.meta.url)
const { buildVersion } = require("./dist/buildInfo.cjs")

export default defineConfig({
  root: "src/client",
  // the Admin UI is served by express under /admin/, so all asset URLs must be relative
  base: "./",
  publicDir: false,
  plugins: [react()],
  define: {
    VENUS_INFLUX_LOADER_BUILD_VERSION: JSON.stringify(buildVersion),
  },
  build: {
    outDir: "../../dist/client",
    emptyOutDir: true,
    sourcemap: true,
  },
  server: {
    open: true,
    proxy: {
      // in dev, forward Admin API and /stream websocket to venus-influx-loader started by npm run watch-influx-loader
      "/admin-api": { target: "http://localhost:8088", auth: "admin:admin" },
      "/stream": { target: "ws://localhost:8088", ws: true, auth: "admin:admin" },
    },
  },
})
